test
Signed-off-by: abarreiro <abarreiro@vmware.com>

diff --git a/.github/workflows/check-mod.yml b/.github/workflows/check-mod.yml
--- a/.github/workflows/check-mod.yml
+++ b/.github/workflows/check-mod.yml
@@ -1,11 +1,11 @@
 name: check-mod
-on: pull_request
-  #pull_request_review:
-  #  types: [submitted]
+on:
+  pull_request_review:
+    types: [submitted]
 
 jobs:
   build:
-    # if: github.event.review.state == 'approved'
+    if: github.event.review.state == 'approved'
     name: Check
     runs-on: ubuntu-latest
 
@@ -18,4 +18,4 @@ jobs:
         run: |
           set +e
           grep 'replace github.com/vmware/go-vcloud-director' go.mod
-          if [ "$?" -eq 0 ]; then echo "ERROR: Found a replaced go.mod. Remove the replacement and retry"; exit 1; else exit 0; fi
+          if [ "$?" -eq 0 ]; then echo "ERROR: Found a replaced go.mod. Remove the replacement before merging"; exit 1; else exit 0; fi
